version: "3.8"
services:
  wordpress:
    container_name: Wordpress
    image: j3ang/customized-bitnami-wordpress:latest
    ports:
      - "4343:8443"
      - "3088:8080"
    volumes:
      - "wordpress_data_latest_new:/bitnami/wordpress"
      - "./composer.json:/composer.json"
      - "./auth.json:/auth.json"
      - "./wp-content/themes:/bitnami/wordpress/wp-content/themes"
      - "${OFFLOAD_PRIVATKEY_HOST_PATH}:${OFFLOAD_PRIVATKEY_SERVER_PATH}" # configure offload gcp access keys json file
      - "./.zshrc:/home/bitnami/.zshrc"
      - ".:/localhost"
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: unless-stopped

  sftp:
    image: j3ang/docker-ssh:latest
    ports:
      - "2202:22"
    volumes:
      - wordpress_data_latest_new:/var/www/wordpress

  mariadb:
    container_name: Database
    image: docker.io/bitnami/mariadb:10.3-debian-10
    ports:
      - 3366:3306
    volumes:
      - mariadb_data:/bitnami/mariadb
      - "./scripts:/scripts"
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    container_name: Phpmyadmin
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    environment:
      - APACHE_HTTP_PORT_NUMBER=8181
      - APACHE_HTTPS_PORT_NUMBER=8143
    ports:
      - 5880:8181
      - 5443:8143
    volumes:
      - phpmyadmin_data:/bitnami/phpmyadmin

  frontend:
    container_name: j3ang-App
    image: node:14.15.1
    ports:
      - 80:3000
    links:
      - wordpress:'0.0.0.0'
    environment:
      - HOST=0.0.0.0
      - WUXT_WP_CONTAINER=wordpress
      - WUXT_PORT_BACKEND=3088
    working_dir: "/var/www/app"
    command: bash -c "yarn install && WUXT_PORT_BACKEND=${WUXT_PORT_BACKEND:-3088}  yarn dev"
    volumes:
      - ./nuxt:/var/www/app

volumes:
  mariadb_data:
    driver: local
  wordpress_data_latest_new:
    driver: local
  phpmyadmin_data:
    driver: local
