version: "3.8"
services:
  wordpress:
    container_name: Wordpress
    image: j3ang/my-custom-bitnami-wordpress:latest
    ports:
      - "443:8443"
      - "3306:3306"
      - "3080:8080"
    volumes:
      - "wordpress_data:/bitnami/wordpress"
      - "./composer.json:/composer.json"
      - "./composer-update.sh:/composer-update.sh"
      - "./wp-content/themes/wuxt:/bitnami/wordpress/wp-content/themes/wuxt"
      - "./.zshrc:/.zshrc"
      - ".:/localhost"

    depends_on:
      - mariadb
    env_file:
      - .env
    restart: unless-stopped

  sftp:
    image: j3ang/docker-ssh:latest
    ports:
      - "2202:22"
    volumes:
      - wordpress_data:/var/www/wordpress

  mariadb:
    container_name: Database
    image: docker.io/bitnami/mariadb:10.3-debian-10
    volumes:
      - mariadb_data:/bitnami/mariadb
      - "./scripts:/scripts"
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    container_name: Phpmyadmin
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    environment:
      - APACHE_HTTP_PORT_NUMBER=8181
      - APACHE_HTTPS_PORT_NUMBER=8143
    ports:
      - 5880:8181
      - 5443:8143
    volumes:
      - phpmyadmin_data:/bitnami/phpmyadmin

  frontend:
    container_name: j3ang-App
    image: node:14.15.0
    ports:
      - 80:3000
    links:
      - wordpress:'0.0.0.0'
    environment:
      - HOST=0.0.0.0
      - WUXT_WP_CONTAINER=wordpress
      - WUXT_PORT_BACKEND=3080
    working_dir: "/var/www/app"
    command: bash -c "yarn install && WUXT_PORT_BACKEND=${WUXT_PORT_BACKEND:-3080}  yarn dev"
    volumes:
      - ./nuxt:/var/www/app

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  phpmyadmin_data:
    driver: local
